In [2]:
!pip install geopandas

Collecting geopandas
  Downloading geopandas-1.1.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: numpy>=1.24 in c:\users\sil-f\anaconda3\lib\site-packages (from geopandas) (2.3.5)
Collecting pyogrio>=0.7.2 (from geopandas)
  Downloading pyogrio-0.12.1-cp313-cp313-win_amd64.whl.metadata (6.0 kB)
Requirement already satisfied: packaging in c:\users\sil-f\anaconda3\lib\site-packages (from geopandas) (25.0)
Requirement already satisfied: pandas>=2.0.0 in c:\users\sil-f\anaconda3\lib\site-packages (from geopandas) (2.3.3)
Collecting pyproj>=3.5.0 (from geopandas)
  Downloading pyproj-3.7.2-cp313-cp313-win_amd64.whl.metadata (31 kB)
Collecting shapely>=2.0.0 (from geopandas)
  Downloading shapely-2.1.2-cp313-cp313-win_amd64.whl.metadata (7.1 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sil-f\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sil-f\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sil-f\anaconda3\lib\site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in c:\users\sil-f\anaconda3\lib\site-packages (from pyogrio>=0.7.2->geopandas) (2025.11.12)
Requirement already satisfied: six>=1.5 in c:\users\sil-f\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Downloading geopandas-1.1.2-py3-none-any.whl (341 kB)
Downloading pyogrio-0.12.1-cp313-cp313-win_amd64.whl (22.9 MB)
   ---------------------------------------- 0.0/22.9 MB ? eta -:--:--
   ----- ---------------------------------- 2.9/22.9 MB 20.3 MB/s eta 0:00:01
   -------- ------------------------------- 5.0/22.9 MB 15.5 MB/s eta 0:00:02
   ---------------- ----------------------- 9.4/22.9 MB 15.8 MB/s eta 0:00:01
   --------------------- ------------------ 12.3/22.9 MB 15.6 MB/s eta 0:00:01
   ------------------------ --------------- 13.9/22.9 MB 13.5 MB/s eta 0:00:01
   -------------------------- ------------- 14.9/22.9 MB 11.9 MB/s eta 0:00:01
   --------------------------- ------------ 15.7/22.9 MB 11.1 MB/s eta 0:00:01
   ----------------------------- ---------- 16.8/22.9 MB 10.3 MB/s eta 0:00:01
   ------------------------------- -------- 17.8/22.9 MB 9.7 MB/s eta 0:00:01
   --------------------------------- ------ 19.1/22.9 MB 9.1 MB/s eta 0:00:01
   ----------------------------------- ---- 20.2/22.9 MB 8.8 MB/s eta 0:00:01
   ------------------------------------- -- 21.2/22.9 MB 8.5 MB/s eta 0:00:01
   -------------------------------------- - 22.3/22.9 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------- 22.9/22.9 MB 7.9 MB/s  0:00:02
Downloading pyproj-3.7.2-cp313-cp313-win_amd64.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ------ --------------------------------- 1.0/6.3 MB 5.6 MB/s eta 0:00:01
   ------------- -------------------------- 2.1/6.3 MB 5.0 MB/s eta 0:00:01
   ------------------- -------------------- 3.1/6.3 MB 5.4 MB/s eta 0:00:01
   ---------------------------- ----------- 4.5/6.3 MB 5.4 MB/s eta 0:00:01
   ---------------------------------- ----- 5.5/6.3 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 5.2 MB/s  0:00:01
Downloading shapely-2.1.2-cp313-cp313-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------------ --------------- 1.0/1.7 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 4.9 MB/s  0:00:00
Installing collected packages: shapely, pyproj, pyogrio, geopandas

   ---------------------------------------- 0/4 [shapely]
   ---------------------------------------- 0/4 [shapely]
   ---------------------------------------- 0/4 [shapely]
   ---------------------------------------- 0/4 [shapely]
   ---------------------------------------- 0/4 [shapely]
   ---------- ----------------------------- 1/4 [pyproj]
   ---------- ----------------------------- 1/4 [pyproj]
   -------------------- ------------------- 2/4 [pyogrio]
   -------------------- ------------------- 2/4 [pyogrio]
   -------------------- ------------------- 2/4 [pyogrio]
   -------------------- ------------------- 2/4 [pyogrio]
   -------------------- ------------------- 2/4 [pyogrio]
   -------------------- ------------------- 2/4 [pyogrio]
   ------------------------------ --------- 3/4 [geopandas]
   ------------------------------ --------- 3/4 [geopandas]
   ------------------------------ --------- 3/4 [geopandas]
   ------------------------------ --------- 3/4 [geopandas]
   ------------------------------ --------- 3/4 [geopandas]
   ---------------------------------------- 4/4 [geopandas]

Successfully installed geopandas-1.1.2 pyogrio-0.12.1 pyproj-3.7.2 shapely-2.1.2

In [1]:
# PASO 1: IMPORTAR Y CARGAR DATOS

import os
import geopandas as gpd
import pandas as pd

# 1. Definición de rutas
ruta_entrada = os.path.join('../../datos/crudos/zonas', '2020_Neighborhood_Tabulation_Areas_(NTAs)_20260118.geojson')

# 2. Carga del dataset geoespacial
gdf_ntas = gpd.read_file(ruta_entrada)


print(f"📊 Registros totales (NYC): {len(gdf_ntas)}")
print(f"🌍 Columnas detectadas: {list(gdf_ntas.columns)}")
display(gdf_ntas.head(5))

📊 Registros totales (NYC): 262
🌍 Columnas detectadas: [':id', ':version', ':created_at', ':updated_at', 'borocode', 'boroname', 'countyfips', 'nta2020', 'ntaname', 'ntaabbrev', 'ntatype', 'cdta2020', 'cdtaname', 'shape_leng', 'shape_area', 'geometry']

,:id,:version,:created_at,:updated_at,borocode,boroname,countyfips,nta2020,ntaname,ntaabbrev,ntatype,cdta2020,cdtaname,shape_leng,shape_area,geometry
0,row-9rke~8csg~x32h,rv-iaad~hgin.v282,2025-11-24 21:27:53.701000+00:00,2025-11-24 21:27:53.701000+00:00,3,Brooklyn,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28919.5611508,35321808.3909,"MULTIPOLYGON (((-73.93213 40.72816, -73.93238 ..."
1,row-6kev-zxyi-52cf,rv-98sh-9jt9.2bdr,2025-11-24 21:27:53.701000+00:00,2025-11-24 21:27:53.701000+00:00,3,Brooklyn,047,BK0102,Williamsburg,Wllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28134.0826611,28852852.9133,"MULTIPOLYGON (((-73.95814 40.7244, -73.95772 4..."
2,row-8yxz.4kik-hwrr,rv-gady.m6h7-vken,2025-11-24 21:27:53.701000+00:00,2025-11-24 21:27:53.701000+00:00,3,Brooklyn,047,BK0103,South Williamsburg,SWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),18250.2800908,15208960.645,"MULTIPOLYGON (((-73.95024 40.70547, -73.94984 ..."
3,row-qcbs_gztc_ygrg,rv-9tne-mmrz~t5xd,2025-11-24 21:27:53.701000+00:00,2025-11-24 21:27:53.701000+00:00,3,Brooklyn,047,BK0104,East Williamsburg,EWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),43184.8003755,52267406.735,"MULTIPOLYGON (((-73.92406 40.71411, -73.92404 ..."
4,row-97cj-vr4j.5jqt,rv-ucv6~gvar~a2pc,2025-11-24 21:27:53.701000+00:00,2025-11-24 21:27:53.701000+00:00,3,Brooklyn,047,BK0201,Brooklyn Heights,BkHts,0,BK02,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,14312.1922849,9982022.78755,"MULTIPOLYGON (((-73.99236 40.68969, -73.99436 ..."

In [2]:
# PASO 2: SELECCIÓN Y LIMPIEZA DE COLUMNAS

# Filtramos por boroname o borocode (Manhattan = 1)
gdf_manhattan = gdf_ntas[
    (gdf_ntas['boroname'] == 'Manhattan') | (gdf_ntas['borocode'] == '1')
].copy()

# Seleccionamos las columnas que realmente aportan valor al análisis espacial
columnas_interes = [
    'borocode', 'boroname', 'nta2020', 'ntaname', 
    'cdta2020', 'cdtaname', 'shape_leng', 'shape_area', 'geometry'
]

gdf_manhattan = gdf_manhattan[columnas_interes]

# Renombrado de variables (menos geometry)
mapeo_columnas = {
    'borocode': 'ID_DISTRITO',
    'boroname': 'NOMBRE_DISTRITO',
    'nta2020': 'ID_ZONA',
    'ntaname': 'NOMBRE_ZONA',
    'cdta2020': 'ID_CDTA',
    'cdtaname': 'NOMBRE_CDTA',
    'shape_area': 'AREA_M2',
    'shape_leng': 'PERIMETRO_M',
}
gdf_manhattan = gdf_manhattan.rename(columns=mapeo_columnas)


print(f"📍 Barrios en Manhattan: {len(gdf_manhattan)}")
print("-" * 70)
display(gdf_manhattan.head(5))

📍 Barrios en Manhattan: 38
----------------------------------------------------------------------

,ID_DISTRITO,NOMBRE_DISTRITO,ID_ZONA,NOMBRE_ZONA,ID_CDTA,NOMBRE_CDTA,PERIMETRO_M,AREA_M2,geometry
118,1,Manhattan,MN0101,Financial District-Battery Park City,MN01,MN01 Financial District-Tribeca (CD 1 Equivalent),44672.4863141,19226758.9064,"MULTIPOLYGON (((-74.00078 40.69429, -74.00096 ..."
119,1,Manhattan,MN0102,Tribeca-Civic Center,MN01,MN01 Financial District-Tribeca (CD 1 Equivalent),21219.504238,13578197.7714,"MULTIPOLYGON (((-73.99931 40.71755, -73.99945 ..."
120,1,Manhattan,MN0191,The Battery-Governors Island-Ellis Island-Libe...,MN01,MN01 Financial District-Tribeca (CD 1 Equivalent),49616.7910027,11993281.8692,"MULTIPOLYGON (((-74.01093 40.68449, -74.01193 ..."
121,1,Manhattan,MN0201,SoHo-Little Italy-Hudson Square,MN02,MN02 Greenwich Village-SoHo (CD 2 Equivalent),18577.1114381,12916761.4511,"MULTIPOLYGON (((-74.00282 40.72836, -74.00272 ..."
122,1,Manhattan,MN0202,Greenwich Village,MN02,MN02 Greenwich Village-SoHo (CD 2 Equivalent),12974.0060903,10600456.4919,"MULTIPOLYGON (((-73.9899 40.73443, -73.98987 4..."

In [26]:
# PASO 3: ESTANDARIZACIÓN Y CONVERSIÓN DE TIPOS DE DATOS (GEOJSON)

# Inspección del tipo de datos
print("\n📊 Resumen de la estructura:")
gdf_manhattan.info()

# Conversión de tipos numéricos y decimales
gdf_manhattan['ID_DISTRITO'] = pd.to_numeric(gdf_manhattan['ID_DISTRITO'], errors='coerce').astype(int)
gdf_manhattan['AREA_M2'] = gdf_manhattan['AREA_M2'].astype(float)
gdf_manhattan['PERIMETRO_M'] = gdf_manhattan['PERIMETRO_M'].astype(float)

# Auditoría final de tipos
print("\n📊 TIPOS DE DATOS FINALES:")
print(gdf_manhattan.dtypes)

📊 Resumen de la estructura:
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 38 entries, 118 to 155
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_DISTRITO      38 non-null     object
 1   NOMBRE_DISTRITO  38 non-null     object
 2   ID_BARRIO        38 non-null     object
 3   NOMBRE_BARRIO    38 non-null     object
 4   ID_CDTA          38 non-null     object
 5   NOMBRE_CDTA      38 non-null     object
 6   PERIMETRO_M      38 non-null     object
 7   AREA_M2          38 non-null     object
 8   geometry         38 non-null     geometry
dtypes: geometry(1), object(8)
memory usage: 3.0+ KB

📊 TIPOS DE DATOS FINALES:
ID_DISTRITO           int64
NOMBRE_DISTRITO      object
ID_BARRIO            object
NOMBRE_BARRIO        object
ID_CDTA              object
NOMBRE_CDTA          object
PERIMETRO_M         float64
AREA_M2             float64
geometry           geometry
dtype: object

In [3]:
# PASO 4: AUDITORÍA DE CALIDAD DE LOS DATOS (MTA)

print("🔍 AUDITORÍA DE CALIDAD")
print("-" * 70)

# Verificamos nulos en las nuevas columnas
nulos = gdf_manhattan.isnull().sum()
print(f"📝 Nulos detectados:\n{nulos}")

# Verificamos que la columna GEOMETRIA sea válida
invalidos = (~gdf_manhattan.geometry.is_valid).sum()
print(f"⚠️ Geometrías inválidas: {invalidos}")

🔍 AUDITORÍA DE CALIDAD
----------------------------------------------------------------------
📝 Nulos detectados:
ID_DISTRITO        0
NOMBRE_DISTRITO    0
ID_ZONA            0
NOMBRE_ZONA        0
ID_CDTA            0
NOMBRE_CDTA        0
PERIMETRO_M        0
AREA_M2            0
geometry           0
dtype: int64
⚠️ Geometrías inválidas: 0

In [4]:
# PASO 5: EXPORTACIÓN FINAL DEL GEOJSON

import os

# Definición del nombre del archivo y ruta para guardar 
carpeta = '../../datos/limpios/zonas'
nombre_archivo = '12_NTAs_Manhattan_Geometry.geojson'
ruta_completa = os.path.join(carpeta, nombre_archivo)


try:
    # Guardamos el archivo en formato GeoJSON
    gdf_manhattan.to_file(ruta_completa, driver='GeoJSON')
    
    print(f"📂 Archivo 12 guardado en: {ruta_completa}")
    print(f"📊 Barrios exportados: {len(gdf_manhattan)}")
    print(f"🌍 Sistema de Coordenadas: {gdf_manhattan.crs}")

except Exception as e:
    print(f"❌ Error al guardar el archivo: {e}")

📂 Archivo 12 guardado en: Datos_Limpios\12_NTAs_Manhattan_Geometry.geojson
📊 Barrios exportados: 38
🌍 Sistema de Coordenadas: EPSG:4326